#Variables

In [1]:
#Diifferent typs of data in python ,how to use variables to reprent data in Python

In [3]:
mymajor="Mathematics"

In [4]:
print(mymajor)

Mathematics


## what are we seeing?
1. we are saving *string"math" to a variable names my major using the qual sign
printing "my major inside the paretheses(), where we put"argument as input variables

In [6]:
mymajor #you cna type varibale name to see its value

'Mathematics'

In [7]:
your_friends_major ="math"

In [11]:
#print two variables simultaneously by using comma
mymajor, your_friends_major

('Mathematics', 'math')

In [12]:
mymajor, your_friends_major ="chemistry","chemistry"

In [13]:
mymajor, your_friends_major #these parethesis mean a" tuple" onject, which we will learn in next few days

('chemistry', 'chemistry')

In [16]:
#what happens if we use a different variable variable name that is not defined yet?
myminor

NameError: name 'myminor' is not defined

In [ ]:
#Traceback halpes you identify the eooro you ade, "NameError" indicates that there's an error in your varibale name

# A few guidelines for naming and using variables
- Variabels names can contain only ** letters, numbers, and underscore" they can start with a letter or an underscore, but not a number
- Spaces are not allowed in you rvaribale names, but underscores cna be used to separate words in variable names
- Avoid using Python fuction names and keywords 
- Variable names should be short and descriptive something people can easy to understand and read
- Lower case number "l" vs number1: capital"0" vs Arabic number 0
- Default is using lowercase for varibale names; capitals are reserved for special cases such as classes we will elanr later.

In [17]:
mymajor_1="Mathematics"
mymajor_1

'Mathematics'

In [18]:
1_mymajor="Mathematics"

SyntaxError: invalid decimal literal (2842859909.py, line 1)

In [19]:
my major="Mathematics"

SyntaxError: invalid syntax (4163882196.py, line 1)

In [20]:
print=" Does this actually work?"#here our print fuction lost its job and became another varibale 

In [21]:
print("Mathematics")

TypeError: 'str' object is not callable

# 2. Strings

In [22]:
#A string is a series of charatcters you can use single quote('') or double quotes ("")around your string 
#to indicate that its a string object

In [23]:
"This is an example"
'This is an example'

'This is an example'

In [24]:
#use single quote and double quotes simultaenously:
'I asked my friend,"would you like to get some ice cream?", but they replied,"Not really".'

'I asked my friend,"would you like to get some ice cream?", but they replied,"Not really".'

In [25]:
#can't we use double quotes to wrap this sentence?
"I asked my friend,"would you like to get some ice cream?", but they replied,"Not really".'"
#here we have three string varibales connected with ramdom varibales whose values are not defined

SyntaxError: invalid syntax (1483439879.py, line 2)

In [27]:
"I asked my friend,\"would you like to get some ice cream?\", but they replied,\"Not really\".'"

'I asked my friend,"would you like to get some ice cream?", but they replied,"Not really".\''

In [30]:
#How to use variables of strings(characters)
first_name = "Kiwon"
last_name = "Lee"


In [31]:
#How to combine these two?
first_name +last_name

'KiwonLee'

In [32]:
first_name +' '+last_name #add an empty space between two string varibales

'Kiwon Lee'

### f strings
f stands for format, python formats the string by replacing the name of any variable in"bracses"{}with its value. We will use this in our workshop

In [33]:
f"{first_name}"

'first_name'

In [36]:
f"{first_name}"

'Kiwon'

In [39]:
f"{first_name} {last_name}"


'Kiwon Lee'

In [40]:
del print# remove a variable

In [41]:
print(f"My first name is{first_name}and my last name is{last_name}.")

My first name isKiwonand my last name isLee.


In [42]:
#How to change case in a string?
full_name="Kiwon Lee"
print(full_name)

Kiwon Lee


In [43]:
full_name.title()#we say we are applying" title""method" to the"full_name"variable


'Kiwon Lee'

In [44]:
?full_name.title

In [45]:
full_name._dir_()#this can be show 

AttributeError: 'str' object has no attribute '_dir_'

In [46]:
full_name.upper()

'KIWON LEE'

In [47]:
full_name #the result of the upper method is not"saved"

'Kiwon Lee'

In [48]:
#if you want to save the result
full_name = full_name.upper()

In [49]:
full_name

'KIWON LEE'

In [50]:
full_name.lower()

'kiwon lee'

## Dealing with spaces
In python, whitespace refers to any nonprinting charaters such as spaces, tabs, the end-of-line symbpls. You might want to use whitespac to orgnize your output for a better readiblity

In [51]:
print("Math is fun")

Math is fun


In [55]:
print("Math \tis \tfun!") #\t for adding "tabs"

Math 	is 	fun!


In [58]:
#How to remove spaces?
example_text ="Math is fun!"

In [59]:
example_text

'Math is fun!'

In [60]:
example_text.rstrip()#strip spaces on the most right

'Math is fun!'

In [61]:
example_text.lstrip()

'Math is fun!'

In [62]:
example_text.strip()#strip every space in the sentence?

'Math is fun!'

In [66]:
#what if we want to remove every space in the sentence?
example_text.replace(" ","")

'Mathisfun!'

In [73]:
##how to check whether a string starts with a certain character/letter
?example_text.startswith

In [71]:
example_text.startswith("M")

True

In [72]:
example_text.startswith("")

True

In [74]:
#index refers to "location", and python start with 0

In [76]:
example_text.lstrip().startswith("M")#You can use multiple methods simultaneously as well

True

In [79]:
#How to remove prefix?
example_text = example_text.strip()

In [80]:
example_text

'Math is fun!'

In [81]:
example_text.removeprefix('Math')

' is fun!'

In [82]:
'Physics'+example_text.removeprefix('Math')

'Physics is fun!'

In [85]:
f"physics{example_text.removeprefix('Math')}"

'physics is fun!'

In [86]:
##Single quote and double quots are interchangeable
##triple quotes?
##triple quotes will be used for "docstrings",wich is used to describe fuctions

In [87]:
def print_message(message):
    """print the input string variale"""
    print(message)

In [88]:
print_message(example_text)

Math is fun!


# 3. Numbers

In [89]:
##Intergers(No decimal points) vs floats(decimal points)

In [91]:
a=2

In [92]:
type(a)

int

In [93]:
b=2.0

In [94]:
type(b)

float

In [96]:
#if you mix an integer and a float in any operaton, you will get a float
a+b

4.0

2+3

In [97]:
2+3

5

In [98]:
2*3

6

In [100]:
#division is an exception: when you divide two integers, the result is always a float.
4/2

2.0

In [103]:
#multiple assignments are also possible 
a,b=2,2.0
print(a,b)

2 2.0


In [106]:
#Constant is a varibale whose value will stay the same throughout the life of the program
#Use upper letters to indicate that you are delaing with a consent
NUM_OF_STUDENTS =25
type(NUM_OF_STUDENTS)

int

In [107]:
##How to deal with large numers?

In [109]:
Canada_populcation= 41000000
Canada_populcation

41000000

In [110]:
Canada_population_2=41_000_000

In [111]:
Canada_population_2

41000000

In [114]:
Canada_population_3 = 41e+6 #e standing for exponential

In [115]:
Canada_population_3

41000000.0

# Numpy package

In [116]:
import numpy as np #abbreviation

In [118]:
a =np.array([1,2,3])
b =np.array([4,5,6])

In [119]:
a

array([1, 2, 3])

In [122]:
a+b 

array([5, 7, 9])

In [121]:
a-b

array([-3, -3, -3])

In [123]:
a*b

array([ 4, 10, 18])

In [125]:
np.dot(a,b)#(=1*4+2*5=3*6)

32

In [126]:
np.exp(1)

2.718281828459045

In [127]:
pi

NameError: name 'pi' is not defined

In [128]:
np.pi

3.141592653589793

In [130]:
np.sin(np.pi/2)

1.0